#==========================================================
#= Articoli Web Service 
#==========================================================

server:
  port: 5051
  
spring:
  application:
    name: ArticoliWebService
#==========================================================
#=  DBMS POSTGRESQL params
#==========================================================
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    password: Alele1411
    url: jdbc:postgresql://localhost:5433/Betashop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

