#==========================================================
#= Articoli Web Service - Versione Base
#==========================================================

# DB endpoint
# http://localhost/login

server:
  port: 5051

spring:
  application:
    name: ProductsWebService

  datasource:
    password: Alele1411
    url: jdbc:postgresql://localhost:5433/betashop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none

      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          jdbc:
            lob:
              non_contextual_creation: true
      show-sql: true
  sql:
    init:
      platform: postgres
      mode: always
